name: Release
on:
  workflow_dispatch:

jobs:
  test:
    uses: streamdeck-linux-gui/streamdeck-linux-gui/.github/workflows/test.yaml@main

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    environment: stable
    outputs:
      version: ${{ steps.semrel.outputs.version }}

    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        name: Release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    environment: stable
    permissions:
      id-token: write
    env: 
      VERSION: ${{ needs.release.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install build tools
        run: python -m pip install --upgrade setuptools wheel twine

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --no-ansi

      - name: Set package version
        run: |
          echo "Version to publish: $VERSION"
          poetry version $VERSION

      - name: Build package
        run: poetry build

      - name: publish pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

      # Commit the version bump back to main branch
      - uses: EndBug/add-and-commit@v9
        with:
          message: "build(version): bump [skip ci]"
          default_author: github_actions
          add: pyproject.toml


